window.APP_CONFIG = {
  categoryRestRules: {
    Stabilization: { setRestMin: 25, betweenRestMin: 25 },
    Mobility: { setRestMin: 15, betweenRestMin: 20 },
    Stretch: { setRestMin: 18, betweenRestMin: 22 },
    Posture: { setRestMin: 18, betweenRestMin: 22 }
  },
  randomPresetCategoryOrder: ['Stabilization', 'Mobility', 'Stretch', 'Posture'],
  unilateralIds: new Set([
    'seated-rotation',
    'seated-side-bend',
    'trap-stretch',
    'levator-stretch',
    'behind-back-sidebend',
    'nerve-glide',
    'bird-dog',
    'dead-bug',
    'lb-single-knee-chest',
    'lb-rotational-stretch',
    'lb-figure-four',
    'lb-hamstring-strap',
    'lb-seated-twist',
    'lb-bird-dog',
    'lb-side-plank-mod'
  ]),
  exerciseLinks: {
    'chin-tuck': 'https://www.youtube.com/results?search_query=chin+tuck+exercise',
    'isometric': 'https://www.youtube.com/results?search_query=isometric+neck+exercise',
    'shoulder-squeeze': 'https://www.youtube.com/results?search_query=shoulder+blade+squeeze+exercise',
    'seated-rotation': 'https://www.youtube.com/results?search_query=seated+neck+rotation+exercise',
    'seated-flexion': 'https://www.youtube.com/results?search_query=seated+neck+flexion+exercise',
    'seated-extension': 'https://www.youtube.com/results?search_query=seated+neck+extension+exercise',
    'seated-side-bend': 'https://www.youtube.com/results?search_query=neck+side+bend+stretch',
    'seated-scapular': 'https://www.youtube.com/results?search_query=seated+scapular+retraction+exercise',
    'bird-dog': 'https://www.youtube.com/results?search_query=bird+dog+exercise',
    'dead-bug': 'https://www.youtube.com/results?search_query=dead+bug+exercise',
    'trap-stretch': 'https://www.youtube.com/results?search_query=upper+trapezius+stretch',
    'levator-stretch': 'https://www.youtube.com/results?search_query=levator+scapulae+stretch',
    'pec-stretch': 'https://www.youtube.com/results?search_query=pectoral+stretch+exercise',
    'wall-angel': 'https://www.youtube.com/results?search_query=wall+angel+exercise',
    'doorway-stretch': 'https://www.youtube.com/results?search_query=doorway+chest+stretch',
    'nerve-glide': 'https://www.youtube.com/results?search_query=median+nerve+glide+exercise',
    'band-seated-row': 'https://www.youtube.com/results?search_query=seated+resistance+band+row',
    'shoulder-protraction-stretch': 'https://www.youtube.com/results?search_query=shoulder+protraction+stretch',
    'behind-back-sidebend': 'https://www.youtube.com/results?search_query=behind+back+shoulder+neck+side+bend+stretch',
    'shoulder-shrugs': 'https://www.youtube.com/results?search_query=shoulder+shrugs+exercise',
    'lb-child-pose': 'https://www.youtube.com/results?search_query=childs+pose+lower+back+stretch',
    'lb-single-knee-chest': 'https://www.youtube.com/results?search_query=single+knee+to+chest+stretch',
    'lb-double-knee-chest': 'https://www.youtube.com/results?search_query=double+knee+to+chest+stretch',
    'lb-cat-cow': 'https://www.youtube.com/results?search_query=cat+cow+exercise+lower+back',
    'lb-rotational-stretch': 'https://www.youtube.com/results?search_query=lower+back+rotational+stretch',
    'lb-figure-four': 'https://www.youtube.com/results?search_query=figure+four+piriformis+stretch',
    'lb-hamstring-strap': 'https://www.youtube.com/results?search_query=hamstring+strap+stretch',
    'lb-sphinx': 'https://www.youtube.com/results?search_query=sphinx+stretch+lower+back',
    'lb-seated-twist': 'https://www.youtube.com/results?search_query=seated+spinal+twist+stretch',
    'lb-pelvic-tilt': 'https://www.youtube.com/results?search_query=pelvic+tilt+exercise+lower+back',
    'lb-glute-bridge': 'https://www.youtube.com/results?search_query=glute+bridge+exercise',
    'lb-bird-dog': 'https://www.youtube.com/results?search_query=bird+dog+exercise+lower+back',
    'lb-dead-bug': 'https://www.youtube.com/results?search_query=dead+bug+core+exercise',
    'lb-side-plank-mod': 'https://www.youtube.com/results?search_query=modified+side+plank+exercise',
    'lb-superman': 'https://www.youtube.com/results?search_query=superman+exercise+lower+back'
  }
};
